In [ ]:
'''
Day1 Numpy 
1.使用前要import numpy as np

2.建立NumPy array有三種方法
range(1,10,2):產生1,3,5,7,9的整型序列
np.arrange(1,10,2):產生array([1,3,5,7,9])
linspace(1,10,num=2):產生array([1,10])

3.NumPy 陣列是同質性的（homogeneous）的物件;Pandas的List可以放不同型態的資料

4.Numpy會放在連續的記憶體位置，Pandas的List則不一定
'''

# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
'''
list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；

tolist() 才能達成多層的型態轉換。
'''

'\nYour Code\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [28]:
# 記得先 Import 正確的套件
import numpy as np
a = np.random.randint(10, size=6) 
print(a)
print('陣列有多少維度：',a.ndim)
print('陣列維度的大小：',a.shape)
print('陣列當中有幾個元素：',a.size)
print('陣列中的資料型態：',a.dtype)
print('陣列中每個元素佔用的空間：',a.itemsize)
print('陣列的元素分組數：',len(a))
print('python中歸類其資料的型態：',type(a))


[7 1 2 1 7 3]
陣列有多少維度： 1
陣列維度的大小： (6,)
陣列當中有幾個元素： 6
陣列中的資料型態： int64
陣列中每個元素佔用的空間： 8
陣列的元素分組數： 6
python中歸類其資料的型態： <class 'numpy.ndarray'>


In [30]:
np.linspace(1,10,num=2)

array([ 1., 10.])

In [18]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print('陣列有多少維度：',b.ndim)
print('陣列維度的大小：',b.shape)
print('陣列當中有幾個元素：',b.size)
print('陣列中的資料型態：',b.dtype)
print('陣列中每個元素佔用的空間：',b.itemsize)
print('陣列的元素分組數：',len(b))
print('python中歸類其資料的型態：',type(b))


[[2 7 3 3]
 [2 6 8 7]
 [6 1 8 2]]
陣列有多少維度： 2
陣列維度的大小： (3, 4)
陣列當中有幾個元素： 12
陣列中的資料型態： int64
陣列中每個元素佔用的空間： 8
陣列的元素分組數： 3
python中歸類其資料的型態： <class 'numpy.ndarray'>


In [19]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print('陣列有多少維度：',c.ndim)
print('陣列維度的大小：',c.shape)
print('陣列當中有幾個元素：',c.size)
print('陣列中的資料型態：',c.dtype)
print('陣列中每個元素佔用的空間：',c.itemsize)
print('陣列的元素分組數：',len(c))
print('python中歸類其資料的型態：',type(c))

[[[1 6]
  [0 8]
  [5 5]]

 [[3 7]
  [4 9]
  [3 3]]]
陣列有多少維度： 3
陣列維度的大小： (2, 3, 2)
陣列當中有幾個元素： 12
陣列中的資料型態： int64
陣列中每個元素佔用的空間： 8
陣列的元素分組數： 2
python中歸類其資料的型態： <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [20]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[5, 7, 5, 0, 3, 8]
[5, 7, 5, 0, 3, 8]


In [21]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[4, 9, 8, 3], [6, 8, 6, 6], [2, 5, 2, 8]]
[array([4, 9, 8, 3]), array([6, 8, 6, 6]), array([2, 5, 2, 8])]


In [22]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[2, 8], [3, 3], [7, 6]], [[3, 1], [1, 5], [2, 7]]]
[array([[2, 8],
       [3, 3],
       [7, 6]]), array([[3, 1],
       [1, 5],
       [2, 7]])]


In [27]:
def tolist(iterable):
    return iterable.tolist(),list(iterable)


print(tolist(a))
print(tolist(b))
print(tolist(c))

([5, 7, 5, 0, 3, 8], [5, 7, 5, 0, 3, 8])
([[4, 9, 8, 3], [6, 8, 6, 6], [2, 5, 2, 8]], [array([4, 9, 8, 3]), array([6, 8, 6, 6]), array([2, 5, 2, 8])])
([[[2, 8], [3, 3], [7, 6]], [[3, 1], [1, 5], [2, 7]]], [array([[2, 8],
       [3, 3],
       [7, 6]]), array([[3, 1],
       [1, 5],
       [2, 7]])])
