# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [ ]:
'''
np.zeros:產生一個都是0的陣列
np.empty:產生一個接近是0的陣列
有些情況下，你只是想初始化一個矩陣為指定尺寸的矩陣，對裡面的初始化資料並不關心，那你可以使用 np.empty 來實現更快的初始化
'''

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [4]:
# 記得先 Import 正確的套件
import numpy as np
from numpy import random


In [18]:
# 參考解答

a = np.random.rand(2, 3)*100
print(a)

A = a.astype(int)
print(A)

[[57.743809   12.16861927 23.29408625]
 [40.1887849   1.8842576  73.23431044]]
[[57 12 23]
 [40  1 73]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [17]:
m = 20
n = 40

a=np.random.randint(20,40,size=(2, 3))
print(a)

[[28 21 27]
 [31 20 23]]
