# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [2]:
import numpy as np
a=np.arange(5)
print(a.sum()) ##是陣列的函數,定義在array下
print(np.sum(a)) #是陣列的函數,定義在np下
print(sum(a)) #是Python 內建函數

[0 1 2 3 4]
10
[0 1 2 3 4]
10
[0 1 2 3 4]
10


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [8]:
import numpy as np
A = np.random.random((5, 5))

A=(A-A.min())/(A.max()-A.min())

print(A)


[[1.         0.65486974 0.54990303 0.08827081 0.5694094 ]
 [0.37296558 0.80980903 0.6283209  0.75946607 0.05436091]
 [0.07279762 0.27956607 0.59105173 0.36380537 0.15113063]
 [0.06135334 0.26231941 0.79667776 0.         0.09689286]
 [0.32130113 0.58268839 0.61079432 0.27423473 0.97387529]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [16]:
B = np.random.random(10)
B[(B.argmax())]=-1
B

array([ 0.95451675,  0.18087505,  0.39571989,  0.97307646,  0.56389185,
        0.70530359,  0.83339229,  0.12291947,  0.88271232, -1.        ])