# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [65]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [66]:
%timeit -n 10 a = 2
Z+=1

#效果最好

10 loops, best of 5: 29.7 ns per loop


In [67]:
%timeit -n 10 a = 2
for i in Z:
    for j in i:
        for k in j:
            i+=1
#使用迴圈效果最不好

10 loops, best of 5: 53.1 ns per loop


In [68]:
%timeit -n 10 a = 2
for i in Z.flat:
    i+=1

10 loops, best of 5: 45 ns per loop


In [69]:
%timeit -n 10 a = 2

for i in np.nditer(Z):
    i=i+1

10 loops, best of 5: 44 ns per loop


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [59]:
import numpy as np

Z = np.random.randint(0,10,50)
print('Array為:')
print(Z)

#np.bincount(Z) array由小到的值，其出現次數，指的是0,1,2,3,4,5,6,7,8,9 其出現的次數分別
a=np.bincount(Z)
print('0,1,2,3,4,5,6,7,8,9依次其出現次數為: ',a)

#np.argmax()找出"np.bincount(Z)"結果中出現最大值的index
b=np.argmax(a) 
print('出現最多次的為: ',b)

#找出array中等於b的index
index=np.where(Z == b )
print('出現最多次的值，位置在Array的index:',index)

Array為:
[7 5 4 3 8 6 9 5 5 8 6 2 1 9 1 2 7 9 5 6 7 7 6 1 2 4 3 3 8 1 7 6 9 5 0 1 5
 4 3 0 4 5 5 5 1 6 1 5 5 1]
0,1,2,3,4,5,6,7,8,9依次其出現次數為:  [ 2  8  3  4  4 11  6  5  3  4]
出現最多次的為:  5
出現最多次的值，位置在Array的index: (array([ 1,  7,  8, 18, 33, 36, 41, 42, 43, 47, 48]),)


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [44]:
#a.tolist()作巢狀的轉換
# list(...)作一層的轉換

a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[1, 4, 7, 3, 1, 3]
[1, 4, 7, 3, 1, 3]
[[8, 3, 8, 7], [3, 7, 9, 7], [3, 6, 2, 8]]
[array([8, 3, 8, 7]), array([3, 7, 9, 7]), array([3, 6, 2, 8])]
[[[9, 8], [3, 0], [5, 3]], [[8, 4], [4, 7], [0, 8]]]
[array([[9, 8],
       [3, 0],
       [5, 3]]), array([[8, 4],
       [4, 7],
       [0, 8]])]


In [55]:
#進階版
def tolist(lierable):
    if type(lierable)!=np.array:
        return lierable
    return [tolist(obj) for obj in lierable]

print(tolist(a))
print()
print(tolist(b))
print()
print(tolist(c))

[1 4 7 3 1 3]

[[8 3 8 7]
 [3 7 9 7]
 [3 6 2 8]]

[[[9 8]
  [3 0]
  [5 3]]

 [[8 4]
  [4 7]
  [0 8]]]
